# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
# User.create(username: 'choyiny', email: 'choyiny@deployingreliable.software', password: 'temppass')
# User.create(username: 'jordan.liu', email: 'jordan.liu@deployingreliable.software', password: 'temppass')


# we want to seed initial query and click logs
# click logs are around 10% of queries.
# 10.times do |index|
#   query_log = QueryLog.create!(first_post_id: rand(1..10), second_post_id: rand(11..20), third_post_id: rand(21..30), search_term: rand(1..100))
#   # do click logs every 10 times
#   if index % 10 == 0
#     a = [query_log.first_post_id, query_log.second_post_id, query_log.third_post_id]
#     ClickLog.create!(query_id: query_log.id, post_id: a.sample)
#   end
# end
first_names = [
  'Emma',
  'Olivia',
  'Ava',
  'Isabella',
  'Sophia',
  'Charlotte',
  'Mia',
  'Amelia',
  'Harper',
  'Evelyn',
  'Abigail',
  'Emily',
  'Elizabeth',
  'Mila',
  'Ella',
  'Avery',
  'Sofia',
  'Camila',
  'Aria',
  'Scarlett',
  'Victoria',
  'Madison',
  'Luna',
  'Grace',
  'Chloe',
  'Penelope',
  'Layla',
  'Riley',
  'Zoey',
  'Nora',
  'Lily',
  'Eleanor',
  'Hannah',
  'Lillian',
  'Addison',
  'Aubrey',
  'Ellie',
  'Stella',
  'Natalie',
  'Zoe',
  'Leah',
  'Hazel',
  'Violet',
  'Aurora',
  'Savannah',
  'Audrey',
  'Brooklyn',
  'Bella',
  'Claire',
  'Skylar',
  'Liam',
  'Noah',
  'William',
  'James',
  'Oliver',
  'Benjamin',
  'Elijah',
  'Lucas',
  'Mason',
  'Logan',
  'Alexander',
  'Ethan',
  'Jacob',
  'Michael',
  'Daniel',
  'Henry',
  'Jackson',
  'Sebastian',
  'Aiden',
  'Matthew',
  'Samuel',
  'David',
  'Joseph',
  'Carter',
  'Owen',
  'Wyatt',
  'John',
  'Jack',
  'Luke',
  'Jayden',
  'Dylan',
  'Grayson',
  'Levi',
  'Isaac',
  'Gabriel',
  'Julian',
  'Mateo',
  'Anthony',
  'Jaxon',
  'Lincoln',
  'Joshua',
  'Christopher',
  'Andrew',
  'Theodore',
  'Caleb',
  'Ryan',
  'Asher',
  'Nathan',
  'Thomas',
  'Leo'
]
last_names = [
  'Smith',
  'Brown',
  'Tremblay',
  'Martin',
  'Roy',
  'Wilson',
  'Macdonald',
  'Gagnon',
  'Johnson',
  'Taylor',
  'Cote',
  'Campbell',
  'Anderson',
  'Leblanc',
  'Lee',
  'Jones',
  'White',
  'Williams',
  'Miller',
  'Thompson',
  'Gauthier',
  'Young',
  'Van',
  'Morin',
  'Bouchard',
  'Scott',
  'Stewart',
  'Belanger',
  'Reid',
  'Pelletier',
  'Moore',
  'Lavoie',
  'King',
  'Robinson',
  'Levesque',
  'Murphy',
  'Fortin',
  'Gagne',
  'Wong',
  'Clark',
  'Johnston',
  'Clarke',
  'Ross',
  'Walker',
  'Thomas',
  'Boucher',
  'Landry',
  'Kelly',
  'Bergeron',
  'Davis',
  'Mitchell',
  'Murray',
  'Poirier',
  'Mcdonald',
  'Richard',
  'Wright',
  'Girard',
  'Lewis',
  'Baker',
  'Roberts',
  'Simard',
  'Graham',
  'Caron',
  'Harris',
  'Jackson',
  'Green',
  'Beaulieu',
  'Fraser',
  'Fournier',
  'Kennedy',
  'Hall',
  'Hill',
  'Chan',
  'Wood',
  'Lapointe',
  'Ouellet',
  'Bell',
  'Dube',
  'Allen',
  'Adams',
  'Cloutier',
  'Bennett',
  'Lefebvre',
  'Watson',
  'Robertson',
  'Walsh',
  'Collins',
  'Evans',
  'Hebert',
  'Hamilton',
  'Cameron',
  'Desjardins',
  'Russell',
  'Nadeau',
  'Cook',
  'Michaud',
  'Morrison',
  'Singh',
  'Grant',
  'Parsons'
]
# create some users
20.times do |index|
  firstname = first_names.sample(1)
  lastname = last_names.sample(1)
  User.create({
    email: "#{firstname}.#{lastname}@gmail.com", 
    password: "temppass",
    first_name: firstname,
    last_name: lastname
  })
end






