name: Publish blog-frontend Docker image to GitHub Package Registry
on:
  push:
    branches:
      - master # on push to master
    paths:
      - blog-frontend/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Copy Repo Files
      uses: actions/checkout@master

    - name: Publish Docker Image to GPR
      uses: machine-learning-apps/gpr-docker-publish@master
      id: docker
      with:
        IMAGE_NAME: 'reliable-blog-frontend'
        TAG: 'latest'
        DOCKERFILE_PATH: 'blog-frontend/Dockerfile'
        BUILD_CONTEXT: 'blog-frontend'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Deploy frontend
      uses: ./.github/actions/deploy-frontend
    env:
      IMAGE_URL: ${{ steps.docker.outputs.IMAGE_URL }}
